---
- name: "CIS Debian 11 Full Hardening"
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: "Include 2.x | Services and Time Synchronization"
      ansible.builtin.include_tasks: tasks/02_services_time_sync.yml

    - name: "Include 3.x | Network and Firewall Hardening"
      ansible.builtin.include_tasks: tasks/03_network_firewall.yml

    - name: "Include 4.x | Audit and Logging Configuration"
      ansible.builtin.include_tasks: tasks/04_audit_and_logs.yml

    - name: "Include 5.x | Access, Authentication, SSH, and Sudo Configuration"
      ansible.builtin.include_tasks: tasks/05_access_auth_ssh_sudo.yml

    - name: "Include 1.x | Access"
      ansible.builtin.include_tasks: tasks/01_me.yml


      
  handlers:
    - name: Restart timeservice
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: restarted

    - name: Restart journald
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted

    - name: Restart syslog service
      ansible.builtin.systemd:
        name: rsyslog
        state: restarted

    - name: restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Remount_tmp
      ansible.builtin.command: mount -o remount /tmp

    - name: Remount_dev_shm
      ansible.builtin.command: mount -o remount /dev/shm
  
    - name: Remount_home
      ansible.builtin.command: mount -o remount /home
      
    - name: Remount_var_tmp
      ansible.builtin.command: mount -o remount /var/tmp
  
    - name: Remount_var_log
      ansible.builtin.command: mount -o remount /var/log
  
    - name: Remount_var_log_audit
      ansible.builtin.command: mount -o remount /var/log/audit
  
    - name: Update_apt_cache
      ansible.builtin.apt:
        update_cache: yes


